Updated workflow according to comments from johanneskoester.
clinical-genomics-uppsala/accel_amplicon_trimming pull request #3
Opened 2017-11-08 13:03 UTC by Smeds

2017-11-15 14:32 UTC, johanneskoester requested changes

2017-11-15 14:32 UTC, johanneskoester commented on rules/accel_amplicon.smk
> +         "{sample}-{unit}.R2.trimmomatic.fastq"]
You can omit the list brackets in such cases.

2017-11-15 14:32 UTC, johanneskoester commented on rules/accel_amplicon.smk
> +            " -g file:" + config["accel_panels"][samples["panel"][sample_name(wildcards)]]["5p_primer_file"]
Why not wildcards.sample?

2017-11-15 14:32 UTC, johanneskoester commented on rules/accel_amplicon.smk
> +    return os.path.split(wildcards.sample)[-1]
This I don't get.

2017-11-17 13:05 UTC, Smeds commented on rules/accel_amplicon.smk
> +    return os.path.split(wildcards.sample)[-1]
It was an attempt of making the rule a bit more generic and not force a specific output folder, when a user decides to include the rule and not run the Snakefile. If the user outputs the trimmed data to a folder this should make sure that, the sample name is extracted correctly. 
Ex:
* trimmed/sample1.R1,trimmomatic_cutadapt.fastq.gz 
* sample1.R1,trimmomatic_cutadapt.fastq.gz 

And that's why I'm not using the wildcard in your question below.

2017-11-17 14:35 UTC, johanneskoester commented on rules/accel_amplicon.smk
> +    return os.path.split(wildcards.sample)[-1]
I see. My feeling is that this might be a bit too much flexibility. The idea of these workflows is that it is always possible for people to modify the workflow if they really need another structure. By implementing too much flexibility readability is hampered, for relatively little benefit. If people want to rewire the DAG (in terms of folders and filenames), it is maybe better to use the wrappers directly.

However, since we are also talking about subfolders now: in general it is a good idea to have every major step of the workflow in a different subfolder. This improves the performance of DAG building, and also makes it easier to find results after the workflow has been completed.

2017-11-20 13:19 UTC, Smeds commented on rules/accel_amplicon.smk
> +    return os.path.split(wildcards.sample)[-1]
ok! Would it then be better to have this as a wrapper instead of a workflow? It's basically a rule with multiple steps, and you would never run it without only wanting the final output. .  Is it possible to write a wrapper with multiple steps? I don't know if it will be possible to write is as a one-liner.

2017-11-20 14:57 UTC, johanneskoester commented on rules/accel_amplicon.smk
> +    return os.path.split(wildcards.sample)[-1]
No I think it makes absolute sense as a workflow. These are clearly separate steps. Merging them into one will only make problems in cluster environments with limited runtime. It will also mean less flexibility.

2017-11-21 07:55 UTC, Smeds commented on rules/accel_amplicon.smk
> +    return os.path.split(wildcards.sample)[-1]
I have now updated the rule so that data will always end up in a folder named trimmed, and removed the option of defining a output folder.

2017-11-22 08:33 UTC, merged

2017-11-22 10:01 UTC, johanneskoester commented on rules/accel_amplicon.smk
> +        qc=temp("logs/trimmed/{sample}-{unit}.cutadapt_STEP1.qc.txt")
One additional question: why don't you use the log directive here for qc, while you it for trimmomatic above?

2017-11-22 10:07 UTC, johanneskoester commented on Snakefile
> +files = [("trimmed",".R1.trimmomatic_cutadapt.fastq.gz"),
I think this would be much more readable as:

```
rule all:
    input:
        expand(["trimmed/{unit.sample}-{unit.unit}.R{read}.trimmomatic_cutadapt.fastq.gz",
                "logs/trimmed/{unit.sample}-{unit.unit}.trimmomatic_cutadapt.qc.txt"], 
               unit=units.reset_index().itertuples(),
               read=[1, 2])
```

2017-11-22 10:13 UTC, johanneskoester commented on rules/accel_amplicon.smk
>              for qc_file in input.qc:
I think you can omit the `str()` below.

2017-11-30 09:26 UTC, johanneskoester commented
@Smeds do you want to implement my last comments, or do you prefer the workflow to be moved into snakemake-workflows before?

2017-12-04 08:45 UTC, Smeds commented on rules/accel_amplicon.smk
> +        qc=temp("logs/trimmed/{sample}-{unit}.cutadapt_STEP1.qc.txt")
I am using the log directive in the latest pull-request https://github.com/clinical-genomics-uppsala/accel_amplicon_trimming/pull/5 and have created a qc output folder for qc originating from cutadapt.

2017-12-04 08:46 UTC, Smeds commented on Snakefile
> +files = [("trimmed",".R1.trimmomatic_cutadapt.fastq.gz"),
This is implemented in the latest pull-request https://github.com/clinical-genomics-uppsala/accel_amplicon_trimming/pull/5

2017-12-04 08:48 UTC, Smeds commented
Pull-request https://github.com/clinical-genomics-uppsala/accel_amplicon_trimming/pull/5 has now been merged into master

2017-12-04 08:54 UTC, johanneskoester commented
Great, thank you! I will fork this now into snakemake-workflows.

2017-12-04 08:55 UTC, johanneskoester commented
Oh wait, I just noticed that the README needs an update with the new sample/unit structure. Do you want to do that before the fork?

2017-12-06 13:58 UTC, Smeds commented
The readme is now updated=)

2017-12-06 16:05 UTC, johanneskoester commented
Thanks!